-- ASTRA MEN account persistence additions
create table if not exists public.wishlist_items(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,product_id uuid not null references public.products(id) on delete cascade,created_at timestamptz not null default now(),unique(user_id,product_id));
create table if not exists public.cart_items(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,variant_id uuid not null references public.product_variants(id) on delete cascade,quantity integer not null check(quantity>0 and quantity<=20),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,variant_id));
create table if not exists public.contact_messages(id uuid primary key default gen_random_uuid(),name text not null,email text not null,phone text not null default '',message text not null,status text not null default 'new' check(status in('new','read','archived')),created_at timestamptz not null default now());
alter table public.wishlist_items enable row level security;alter table public.cart_items enable row level security;alter table public.contact_messages enable row level security;
grant select,insert,delete on public.wishlist_items to authenticated;grant select,insert,update,delete on public.cart_items to authenticated;revoke all on public.contact_messages from anon,authenticated;
drop policy if exists wishlist_items_select_own on public.wishlist_items;create policy wishlist_items_select_own on public.wishlist_items for select to authenticated using((select auth.uid())=user_id);
drop policy if exists wishlist_items_insert_own on public.wishlist_items;create policy wishlist_items_insert_own on public.wishlist_items for insert to authenticated with check((select auth.uid())=user_id);
drop policy if exists wishlist_items_delete_own on public.wishlist_items;create policy wishlist_items_delete_own on public.wishlist_items for delete to authenticated using((select auth.uid())=user_id);
drop policy if exists cart_items_select_own on public.cart_items;create policy cart_items_select_own on public.cart_items for select to authenticated using((select auth.uid())=user_id);
drop policy if exists cart_items_insert_own on public.cart_items;create policy cart_items_insert_own on public.cart_items for insert to authenticated with check((select auth.uid())=user_id);
drop policy if exists cart_items_update_own on public.cart_items;create policy cart_items_update_own on public.cart_items for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
drop policy if exists cart_items_delete_own on public.cart_items;create policy cart_items_delete_own on public.cart_items for delete to authenticated using((select auth.uid())=user_id);
create or replace function public.save_contact_message(p_name text,p_email text,p_phone text,p_message text) returns uuid language plpgsql security definer set search_path=public,pg_catalog as $$
declare v_id uuid; begin if length(trim(coalesce(p_name,'')))<2 then raise exception 'Please provide your name'; end if; if p_email !~* '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$' then raise exception 'Please provide a valid email'; end if; if length(trim(coalesce(p_message,'')))<10 then raise exception 'Please provide a little more detail'; end if; insert into public.contact_messages(name,email,phone,message) values(trim(p_name),lower(trim(p_email)),trim(coalesce(p_phone,'')),trim(p_message)) returning id into v_id; return v_id; end; $$;
grant execute on function public.save_contact_message(text,text,text,text) to anon,authenticated;
drop policy if exists contact_no_read on public.contact_messages;create policy contact_no_read on public.contact_messages for select to anon,authenticated using(false);
insert into public.categories(name,slug,description,image) values('Hoodies','hoodies','Soft brushed layers for off-duty days.',null),('Jackets','jackets','City-ready outer layers with clean structure.',null),('Jeans','jeans','Easy denim fits made for repeat wear.',null),('Trousers','trousers','Tailored-relaxed trousers for everyday rotation.',null),('Shorts','shorts','Relaxed summer silhouettes.',null),('Sweaters','sweaters','Textured knit layers for cooler days.',null),('Polos','polos','Elevated everyday collars and clean lines.',null),('Accessories','accessories','Small details that finish the look.',null) on conflict(slug) do nothing;